# Generated by Django 4.2 on 2023-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(default='Not Available', max_length=254)),
                ('city', models.CharField(default='Not Available', max_length=254)),
                ('state', models.CharField(default='Not Available', max_length=254)),
                ('country', models.CharField(default='Not Available', max_length=254)),
                ('enrolled_courses', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=70)),
                ('stu_password', models.CharField(max_length=64)),
            ],
        ),
    ]
