# Generated by Django 4.1.5 on 2023-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0002_student_enrolled_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.CharField(default="Not Available", max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="country",
            field=models.CharField(default="Not Available", max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="state",
            field=models.CharField(default="Not Available", max_length=254),
        ),
    ]
