# Generated by Django 4.1.5 on 2023-01-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0004_studentregistration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentRegistration",
            new_name="StudentReg",
        ),
    ]
